name: My First Workflow
on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - name: Print your name
        run: echo "yug"
  say-bye:
     runs-on: ubuntu-Latest
     steps:
      -name: say bye
        run: echo "byee from 2nd job"